# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
      UPSTREAM: ssh://git@bitbucket.ase.in.tum.de:7999/eist22t02/eist22t02-goats.git
      BITBUCKET_PUB_KEY: "[bitbucket.ase.in.tum.de]:7999,[131.159.89.140]:7999 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCO2i69e5LJibEDwVrwG9edX+xqeRB/Do+C8dNclgB5lFJjA5MlTFAZ4WewbLBeGXGAc5O64ckBlI82+FI1GwIkiKRoi/9qe+NGLmZFsjBRSz2fHLfKo/iEa8ytPP9E4iql1u7Rl+pnmY2claJ+ABQOt4XQgLWjYcIBHWpwhQ9tRjg73zUI/n/PKyEnODR14bEzJ/fBmTMgnm1ZdtSPViqLmByXgjgorCWPsRA3DrPsH3A9ncietUPj/qRbsWsPhiKK1yXXaKDHDgRD7ennVrwCAYG2hhTZEbZcjE8bbe9UY9WrRtoWLFKB/xDTn7pRv+ZxqXlcoP224we7J9s2ke1H"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: ./gradlew clean test
    
    - name: Set up remote
      run: git remote add upstream ${{env.UPSTREAM}}

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: |
          ${{ secrets.PRIVATE_KEY }}

    - name: Copy ssh public_key
      run: echo "${{SECRETS.PUBLIC_KEY}}" > ~/.ssh/id_rsa.pub

    - name: Add bitbucket to known SSH-HOST
      run: echo ${{env.BITBUCKET_PUB_KEY}} >> ~/.ssh/known_hosts

    - name: Pull origin
      run: git fetch --unshallow

    - name: Specify Identity in case of rebasing
      run: git config --global user.email "organisation-name@github.com" && git config --global user.name "GitHub Action Runner"

    - name: Fix merge conflicts if any
      run: git pull --rebase upstream main

    - name: Git push to other repo
      run: git push upstream
    
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: babyygemperor
        password: ${{ secrets.PAT }}
    - name: Build the Docker image
      run: ./gradlew bootBuildImage --imageName=springio/gs-spring-boot-docker
    - name: Convert IMAGE_NAME to lower_case
      run: |
        echo "REPO=${IMAGE_NAME,,}" >>${GITHUB_ENV}
    - name: Docker tag
      run: docker tag springio/gs-spring-boot-docker $REPO
    - name: Push image to registry
      run: docker push $REPO
    - name: Docker ls
      run: docker images
